### ISSUE TITLE
Recommend IntelliJ IDEA

### ISSUE THREAD

**Issue by yooksi** [FWolfe/Zomboid-Modding-Guide#6]
Under `Required Tools (software)` we are currently recommending Notepad++ as the preferred text editor, however as mentioned [here](https://github.com/FWolfe/Zomboid-Modding-Guide/pull/4#issuecomment-757415929) in PR https://github.com/FWolfe/Zomboid-Modding-Guide/pull/4 we should be promoting the use of IDE over text editors such as Notepad++. 

The best (or the smartest) Java IDE on the market is IntelliJ IDEA.

**Comment by FWolfe** [comment]
I'd prefer to keep the **required** tools to strictly whats needed (minimal requirements) instead of recommended stuff.

The reason Notepad++ was chosen for a example exactly because its a text editor and not a IDE, and because its often the most commonly used.

IDE's are great and all, but often overkill unless you're actually a developer and need the extensive features they provide. Most have large learning curves to use effectively, or to learn to navigate all the features. 
As a prime example, the IntelliJ IDEA community edition  weighs in at a 600-700mb download (before install), which is entirely excessive to edit recipes or other scripts .txt files, or do minor Lua editing.

On a personal note, I prefer to use Atom for PZ related projects.

**Comment by yooksi** [comment]
> I'd prefer to keep the required tools to strictly whats needed (minimal requirements) instead of recommended stuff.

The use of *required* word here is not technically accurate, and neither is saying that there are such things as minimal requirements to create mods. The only **real** minimal requirements to create mods are a valid game installation and *any* text editor (including standard Windows notepad), everything else is a recommendation.

> The reason Notepad++ was chosen for a example exactly because its a text editor and not a IDE, and because its often the most commonly used.

I agree that Notepad++ should be included in that list as the most basic tool in the modding toolkit, but not for the reasons you just listed. We should be recommending tools based on their qualities as opposed to how popular they are, although I understand the logic behind recommending tools that modders can easily get community support for.

> IDE's are great and all, but often overkill unless you're actually a developer and need the extensive features they provide. Most have large learning curves to use effectively, or to learn to navigate all the features.

Just because you are not a professional developer doesn't mean you should not use the tools they use. One could argue the same for Notepad++ as it is mostly used by developers (hobbyist and professionals) who need the extensive features it provides, and it has a fairly steep learning curve to use effectively or to learn to navigate all it's features. I've been using Notepad++ for a very long time and have used many plugins for it and still only know only a portion of features it has to offer.

> As a prime example, the IntelliJ IDEA community edition weighs in at a 600-700mb download (before install), which is entirely excessive to edit recipes or other scripts .txt files, or do minor Lua editing.

I agree with this and this is why I think we should recommend Notepad++ as an **essential** tool and IntelliJ as a **recommended** tool for advanced Lua modding. There is no reason to be setting low standards, people can choose for themselves what they are comfortable with using, our job should be to inform them the **what** and **how**.

I would also like to note that I am preparing to write complete documentation on how to setup the modding environment with IntelliJ and would like to do so as part of this guide. However we first have to start recommending the IDE itself.

**Comment by FWolfe** [comment]
If you want to create a guide for setting up a IntelliJ env for modding, I'd fully support adding that to the guide. I'm sure some people will probably find it quite useful.  However I can't support having the IDE as a default recommendation to point new users at, especially since I personally dislike the IDE and refuse to use it myself. 

None of the software in the required tools section should read a recommendation or endorsement. Everything (except missing mapping section) that is currently listed there is meant to be a example only. Sure I could have used Windows Notepad instead of Notepad++ as a example. I even considered it to put emphasis on the fact no special tools are required, but I'm not a windows user.

I'd like to add a section that includes "useful tools" such as decompilers and lists of text editors & IDE's with pros and cons to help people choose, but I really dislike the idea of the guide making blanket recommendations on software.

**Comment by yooksi** [comment]
> None of the software in the required tools section should read a recommendation or endorsement. Everything (except missing mapping section) that is currently listed there is meant to be a example only.

This should probably be stated clearly in the guide not to mislead readers.

> I'd like to add a section that includes "useful tools" such as decompilers and lists of text editors & IDE's with pros and cons to help people choose, but I really dislike the idea of the guide making blanket recommendations on software.

That is fair if you want the guide to be more focused on the modding aspects as opposed to talking about tools and development environments. Perhaps this is something I will need to move into a separate guide that only focuses on that.

**Comment by yooksi** [comment]
> I can't support having the IDE as a default recommendation to point new users at, especially since I personally dislike the IDE and refuse to use it myself.

I respect that point of view, and with that we can consider this issue resolved.
